shuttle-hq/shuttle-examples

- axum/websocket/src/lib.rs
- axum/websocket/static/index.html
The example was not working locally due to the hardcoded wss protocol.
This PR fixes that, formats the html using prettier and avoids `datetime` in favor of `date_time`.
> fix(axum): fixes ws protocol

- actix-web/websocket-actorless/Cargo.toml
- actix-web/websocket-actorless/Shuttle.toml
- actix-web/websocket-actorless/src/lib.rs
- actix-web/websocket-actorless/static/index.html
Websocket example based on the axum one. Same example as in #11 but without using actors at all
> feat(actix): actorless ws example

- actix-web/postgres/Cargo.toml
- actix-web/websocket-actorless/Cargo.toml
- axum/static-files/Cargo.toml
- axum/static-next-server/Cargo.toml
- axum/websocket/Cargo.toml
- poem/mongodb/Cargo.toml
- poem/postgres/Cargo.toml
- poise/hello-world/Cargo.toml
- rocket/persist/Cargo.toml
- rocket/postgres/Cargo.toml
- rocket/secrets/Cargo.toml
- rocket/url-shortener/Cargo.toml
- serenity/hello-world/Cargo.toml
- serenity/postgres/Cargo.toml
- thruster/postgres/Cargo.toml
- tide/postgres/Cargo.toml
Changes needed to let the CI go green
> misc: go green

- actix-web/hello-world/Cargo.toml
- actix-web/postgres/Cargo.toml
- actix-web/websocket-actorless/Cargo.toml
- axum/hello-world/Cargo.toml
- axum/static-files/Cargo.toml
- axum/static-next-server/Cargo.toml
- axum/websocket/Cargo.toml
- poem/hello-world/Cargo.toml
- poem/mongodb/Cargo.toml
- poem/postgres/Cargo.toml
- poise/hello-world/Cargo.toml
- rocket/authentication/Cargo.toml
- rocket/hello-world/Cargo.toml
- rocket/persist/Cargo.toml
- rocket/postgres/Cargo.toml
- rocket/secrets/Cargo.toml
- rocket/url-shortener/Cargo.toml
- salvo/hello-world/Cargo.toml
- serenity/hello-world/Cargo.toml
- serenity/postgres/Cargo.toml
- thruster/hello-world/Cargo.toml
- thruster/postgres/Cargo.toml
- tide/hello-world/Cargo.toml
- tide/postgres/Cargo.toml
- tower/hello-world/Cargo.toml
- warp/hello-world/Cargo.toml
> misc: v0.12.0-rc1

- rocket/workspace/Cargo.toml
- rocket/workspace/hello-world/Cargo.toml
- rocket/workspace/hello-world/src/main.rs
- rocket/workspace/shared/Cargo.toml
- rocket/workspace/shared/src/lib.rs
Adds an example to show how workspaces can be used
> feat: workspace example

- README.md
- rocket/authentication/README.md
- rocket/persist/README.md
- rocket/url-shortener/README.md
Merge this before the release of https://github.com/shuttle-hq/shuttle/pull/771 (0.14.0 ?)
> Update project cmd

- actix-web/hello-world/src/main.rs
- axum/hello-world/src/main.rs
- next/hello-world/src/lib.rs
- poem/hello-world/src/main.rs
- rocket/hello-world/src/main.rs
- salvo/hello-world/src/main.rs
- thruster/hello-world/src/main.rs
- tide/hello-world/src/main.rs
https://github.com/shuttle-hq/shuttle/issues/841
Related PR in shuttle repo: https://github.com/shuttle-hq/shuttle/pull/863
> feat: changing '/hello' routes to '/'

- custom/none/Cargo.toml
- custom/none/src/main.rs
Replaces https://github.com/shuttle-hq/shuttle-examples/pull/57
> feat: template for empty custom service

- axum/hello-world/Cargo.toml
- axum/static-files/Cargo.toml
- axum/static-files/src/main.rs
- axum/websocket/Cargo.toml
- axum/websocket/src/main.rs
- rocket/workspace/hello-world/src/main.rs
I replaced the static folder example with a simple ServeDir, since serving "known files" and serving a SPA are different things. I intend to add a SPA example. I will also add these to the docs.
All examples were tested locally.
> Update & simplify axum examples, bump versions

- README.md
Linked in the "Community Examples" is a template for a fullstack webapp that is entirely Rust. I was not sure if this or adding the example directly into this repo was preferable. I would be happy to contribute either way.
> Added a fullstack Rust template

- README.md
Here is my Yew web app example.  Pull request submitted here instead of at awesome-shuttle.
> improvement: add axum yew webapp example

- axum/turso/Cargo.toml
Update the libsql-client version to 0.32.0 and removed the pin to version 0.30.1 in the Axum Turso example.
Didn't run any tests.
> chore: update libsql-client version in axum turso

- axum/turso/Cargo.toml
> chore: update libsql-client version in axum turso (#100)

- axum/postgres/migrations/1_schema.sql
Fixes https://github.com/shuttle-hq/shuttle-docs/issues/212
CI fails due to rocket rc4 + no lockfiles in this repo.  Will be solved in https://github.com/shuttle-hq/shuttle/issues/1363
> fix: migration filename

- rocket/dyn-templates/Cargo.toml
- rocket/hello-world/Cargo.toml
- rocket/jwt-authentication/Cargo.toml
- rocket/jwt-authentication/src/claims.rs
- rocket/persist/Cargo.toml
- rocket/persist/src/main.rs
- rocket/postgres/Cargo.toml
- rocket/postgres/src/main.rs
- rocket/secrets/Cargo.toml
- rocket/static-files/Cargo.toml
- rocket/url-shortener/Cargo.toml
- rocket/workspace/hello-world/Cargo.toml
Updated Rocket to 0.5.0-rc.4
Ran all the Rocket-related examples and they compiled and worked locally.
> Improvement shuttle rocket rc4

- rocket/dyn-templates/Cargo.toml
- rocket/hello-world/Cargo.toml
- rocket/jwt-authentication/Cargo.toml
- rocket/persist/Cargo.toml
- rocket/postgres/Cargo.toml
- rocket/secrets/Cargo.toml
- rocket/static-files/Cargo.toml
- rocket/url-shortener/Cargo.toml
- rocket/workspace/hello-world/Cargo.toml
Updated the shuttle-rocket examples to rocket 0.5.0 stable.
Ran all examples and they compiled and ran properly.
> Improvement shuttle rocket 0.5

- actix-web/postgres/Cargo.toml
- axum/postgres/Cargo.toml
- custom-resource/pdo/src/lib.rs
- fullstack-templates/saas/Cargo.toml
- fullstack-templates/saas/backend/Cargo.toml
- poem/hello-world/Cargo.toml
- poem/mongodb/Cargo.toml
- poem/postgres/Cargo.toml
- rocket/postgres/Cargo.toml
- rocket/url-shortener/Cargo.toml
- serenity/postgres/Cargo.toml
- serenity/postgres/src/main.rs
- thruster/postgres/Cargo.toml
- tide/postgres/Cargo.toml
> feat: update everything to new ResourceBuilder + feature flags

- poise/hello-world/Cargo.toml
- poise/hello-world/Shuttle.toml
- poise/hello-world/src/main.rs
- serenity/hello-world/Cargo.toml
- serenity/hello-world/Shuttle.toml
- serenity/postgres/Cargo.toml
- serenity/postgres/Shuttle.toml
- serenity/postgres/src/main.rs
goes with https://github.com/shuttle-hq/shuttle/pull/1521
ran CI locally on all 3 changed examples
> feat: update serenity and poise examples to use serenity 0.12

- README.md
- shuttle-cron/.gitignore
- shuttle-cron/Cargo.toml
- shuttle-cron/README.md
- shuttle-cron/src/main.rs
Adds a `shuttle-cron` example in reference to a created article this week.
Manual testing shows that it works locally
> feat: cron example with apalis

- axum/turso/Cargo.toml
- axum/turso/src/main.rs
Update existing turso example to go along with https://github.com/shuttle-hq/shuttle/pull/1531
Ran locally, both inserting and getting users.
> feat(shuttle-turso): update turso example to use libsql

- axum/htmx-crud/.gitignore
- axum/htmx-crud/.prettierrc.toml
- axum/htmx-crud/Cargo.toml
- axum/htmx-crud/README.md
- axum/htmx-crud/Shuttle.toml
- axum/htmx-crud/migrations/20231018144859_init.down.sql
- axum/htmx-crud/migrations/20231018144859_init.up.sql
- axum/htmx-crud/src/errors.rs
- axum/htmx-crud/src/main.rs
- axum/htmx-crud/src/models.rs
- axum/htmx-crud/src/router.rs
- axum/htmx-crud/src/routes.rs
- axum/htmx-crud/src/templates.rs
- axum/htmx-crud/templates/base.html
- axum/htmx-crud/templates/index.html
- axum/htmx-crud/templates/stream.html
- axum/htmx-crud/templates/styles.css
- axum/htmx-crud/templates/todo.html
- axum/htmx-crud/templates/todos.html
Adds the htmx template (with some upgrades) from this article: https://www.shuttle.rs/blog/2023/10/25/htmx-with-rust
Tested locally.
Do we want to add integration tests to these templates?
> feat: htmx template

- axum/turso/Cargo.toml
- axum/turso/src/main.rs
Bump `libsql` dependency in `axum/turso` example.
> chore: update libsql dep in axum/turso example

- poem/hello-world/Cargo.toml
- poem/mongodb/Cargo.toml
Upgrade poem version
[#1713 ](https://github.com/shuttle-hq/shuttle/issues/1713)
> feat: bump poem version

- axum/qdrant/Cargo.toml
- axum/qdrant/src/main.rs
Update qdrant example to match https://github.com/shuttle-hq/shuttle/pull/1821
It compiles with the PR version of shuttle-qdrant.
> chore: upgrade qdrant to 1.10.1

- fullstack-templates/saas/backend/src/dashboard.rs
- loco/hello-world/Cargo.toml
- loco/hello-world/README.md
- loco/hello-world/src/bin/main.rs
- loco/hello-world/src/controllers/home.rs
Bump loco framework version to 0.9.0
> bump loco version to 0.9.0

- shuttle-cron/Cargo.toml
- shuttle-cron/src/main.rs
- This change updates the cron example to the latest version of apalis
- It also adds the ability to persist cronjobs to the postgres db
> chore: update to latest version and persist cron jobs

- actix-web/README.md
The word "and" was missing from the sentence. Added it.
Not tested. Just a doc change.
> docs: add missing word

- axum/hello-world/Cargo.toml
- axum/htmx-crud/Cargo.toml
- axum/jwt-authentication/Cargo.toml
- axum/metadata/Cargo.toml
- axum/oauth2/Cargo.toml
- axum/openai/Cargo.toml
- axum/postgres/Cargo.toml
- axum/qdrant/Cargo.toml
- axum/static-files/Cargo.toml
- axum/turso/Cargo.toml
- axum/websocket/Cargo.toml
- bevy/hello-world/server/Cargo.toml
- custom-resource/pdo/Cargo.toml
- fullstack-templates/saas/backend/Cargo.toml
- loco/hello-world/Cargo.toml
- other/feature-flags/Cargo.toml
- other/standalone-binary/Cargo.toml
bump hello world to 0.8, leaves rest at 0.7
https://github.com/shuttle-hq/shuttle/pull/1951
> feat: use axum 0.7/0.8 feature flags

- mcp/mcp-sse/Cargo.toml
- mcp/mcp-sse/README.md
- mcp/mcp-sse/src/main.rs
- mcp/mcp-sse/src/mcp_service.rs
- templates.toml
New template added for a ready to deploy SSE transport MCP server to Shuttle.
> New Template: SSE MCP Server
