shuttle-hq/shuttle-examples

- axum/hello-world/Cargo.toml
- axum/websocket/Cargo.toml
- poem/hello-world/Cargo.toml
- poem/mongodb/Cargo.toml
- poem/postgres/Cargo.toml
- rocket/authentication/Cargo.toml
- rocket/persist/Cargo.toml
- rocket/postgres/Cargo.toml
- rocket/secrets/Cargo.toml
- rocket/url-shortener/Cargo.toml
- salvo/hello-world/Cargo.toml
- serenity/hello-world/Cargo.toml
- serenity/postgres/Cargo.toml
- thruster/postgres/Cargo.toml
- tide/postgres/Cargo.toml
- tower/hello-world/Cargo.toml
- warp/hello-world/Cargo.toml
This PR bumps all dependencies in the examples. A lot of these will break unless they are used with the updated `shuttle-service` deps in https://github.com/shuttle-hq/shuttle/pull/495. Meaning this branch should not be merged until that is released.
Note: When merging this, make sure to set the gitmodule branch in shuttle `main` to examples `main`. It is currently set to this branch until this is merged.
> feat: bump example deps

- actix-web/README.md
- actix-web/hello-world/Cargo.toml
- actix-web/hello-world/src/lib.rs
- actix-web/postgres/Cargo.toml
- actix-web/postgres/schema.sql
- actix-web/postgres/src/lib.rs
The actix integration was not compatible with shared state (PgPool does not implement copy), so I removed the Copy bound from the examples and in service: https://github.com/shuttle-hq/shuttle/pull/523. I also added a postgres example for actix, and removed the unnecessary `actix-service` dep.
> feat: add actix postgres example

- axum/static-next-server/src/lib.rs
The index.html generated by create-next-app assumes the assets are in `.`, so if we use `/assets` we will just see a page with text, no css, svgs etc.
> fix: path to serve assets from

- rustfmt.toml
Updated example to use the same `rustfmt.toml` from the base `shuttle` repo.
> style: Added rustfmt.toml

- salvo/hello-world/Cargo.toml
Bumps salvo, this should be merged before the 0.17 release and merged into main before the examples submodule in shuttle is updated with 0.17 examples.
Tested by running locally against the updated shuttle-salvo service.
> chore: bump salvo

- fullstack-templates/saas/backend/src/main.rs
The example doesnt compile.
Fixed the call to `grab_secrets` and the returned tuple.
```
error[E0425]: cannot find value `stripe_sub_price` in this scope
--> src/main.rs:55:9
|
55 |         stripe_sub_price,
|         ^^^^^^^^^^^^^^^^ not found in this scope
error[E0308]: mismatched types
--> src/main.rs:100:5
|
79  | fn grab_secrets(secrets: shuttle_secrets::SecretStore) -> (String, String, String, String) {
|                                                           -------------------------------- expected `(std::string::String, std::string::String, std::string::String, std::string::String)` because of return type
...
100 |     (stripe_key, stripe_sub_price, mailgun_key, mailgun_url, domain)
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected a tuple with 4 …
```
> Fix call to grab_secrets

- axum/with-state/Cargo.toml
- axum/with-state/src/main.rs
Adds a `axum/with-state` example project showing off usage of `axum::State` with an updated `AxumService` from [this PR](https://github.com/shuttle-hq/shuttle/pull/924).
~Draft for now as I'm waiting for the other PR to be merged to remove local dependencies.~ Done.
> feat: Add an axum/with-state example using updated generic AxumService

- README.md
- tracing/axum-logs-endpoint/Cargo.toml
- tracing/axum-logs-endpoint/Shuttle.toml
- tracing/axum-logs-endpoint/src/logger.rs
- tracing/axum-logs-endpoint/src/main.rs
- tracing/axum-logs-endpoint/src/state.rs
- tracing/custom-layer/Cargo.toml
- tracing/custom-layer/Shuttle.toml
- tracing/custom-layer/src/main.rs
In addition to [this new feature](https://github.com/shuttle-hq/shuttle/pull/1027) I also created these two examples to show off how to use it. The `axum-logs-endpoint` example exsits for testing purposes as requested.
> feat: examples for injecting a custom tracing layer

- rocket/dyn-templates/Rocket.toml
- rocket/dyn-templates/src/main.rs
- rocket/dyn-templates/templates/index.html.hbs
Thanks to https://github.com/shuttle-hq/shuttle/pull/1050 we can now use `Rocket.toml` to configure rocket static assets directory, which is the convenctional way to do it.
> feat: rocket static files with rocket config

- fullstack-templates/saas/backend/src/auth.rs
The auth should not only return `Ok/Err` - it actually is supposed to return either `Ok(true)`, `Ok(false)` or `Err(e)`. 
This should have been updated a while ago but unfortunately I got sidetracked.
Manual
> feat: fix auth for SaaS template

- axum/turso/Cargo.toml
Reverts the Turso library update. See shuttle-hq/shuttle#1355
Using the local runner.
> bug: revert turso version update

- .github/pull_request_template.md
We no longer actively use the develop branch, when the need arises to test several PRs together without merging to main, we can rather create a short-lived feature branch.
> chore: remove develop branch suggestion from pr template

- axum/hello-world/Cargo.toml
- axum/jwt-authentication/Cargo.toml
- axum/jwt-authentication/src/main.rs
- axum/metadata/Cargo.toml
- axum/postgres/Cargo.toml
- axum/static-files/Cargo.toml
- axum/static-next-server/Cargo.toml
- axum/static-next-server/src/main.rs
- axum/turso/Cargo.toml
- axum/websocket/Cargo.toml
- axum/websocket/src/main.rs
- axum/with-state/Cargo.toml
- custom-resource/pdo/Cargo.toml
- custom-service/request-scheduler/Cargo.toml
- custom-service/request-scheduler/src/lib.rs
- fullstack-templates/saas/backend/Cargo.toml
- fullstack-templates/saas/backend/src/auth.rs
- fullstack-templates/saas/backend/src/main.rs
- other/standalone-binary/Cargo.toml
- other/standalone-binary/src/bin/standalone.rs
Checked the ones with bigger changes locally. CI will fail unless we change the workflow to checkout the main branch of the main repo, which might not be desired on a main branch. (an argument for using main+develop) :man_shrugging:
> chore: update axum examples to axum 0.7

- fullstack-templates/saas/package.json
To address user-reported crash issues, as discussed in the Discord thread [https://discord.com/channels/803236282088161321/1203990888041160804/1203991607268089887], I've appended --idle-minutes 0 to the start command in package.json. This addition is aimed at preventing idle-induced crashes. Additionally, I've introduced a restart command with the same --idle-minutes 0 parameter to further enhance application reliability and user experience.
All information has been confirmed in the Discord by users
> Add --idle-minutes 0 and restart command in package.json

- rocket/jwt-authentication/src/claims.rs
`chrono::TimeDelta::minutes` to `chrono::TimeDelta::try_minutes`, with `.expect`
https://github.com/shuttle-hq/shuttle-examples/blob/c92718eabe34da02f320df45eb2abd75980e9ada/rocket/jwt-authentication/src/claims.rs#L21
CI run on fork: https://github.com/supleed2/shuttle-examples/actions/runs/8187671386
> fix: replace deprecated fn call in example `rocket/jwt-authentication`

- axum/turso/src/main.rs
Updating the Turso example to match the new macro annotation output, as seen on https://github.com/shuttle-hq/shuttle/pull/1747.
> fix: Change output type from macro on Turso example

- fullstack-templates/saas/turbowatch.ts
This MR introduces the `{ shell: true }` option to the spawn command in [`turbowatch.ts`](https://github.com/shuttle-hq/shuttle-examples/blob/c20e19e908a0d327bf33603164247e621b4b1e2a/fullstack-templates/saas/turbowatch.ts#L15-L18) for the [`fullstack-templates/saas`](https://github.com/shuttle-hq/shuttle-examples/tree/main/fullstack-templates/saas) template.
Please see #175 for further details.
Closes #175 
1. `cargo shuttle init`
2. Select the [`fullstack-templates/saas`](https://github.com/shuttle-hq/shuttle-examples/tree/main/fullstack-templates/saas) template
3. `npm install`
4. `npm run dev`
I observed the front-end to successfully build, instead of throwing `EINVAL`.
> fix: Add shell true to turbowatch in `fullstack-templates/saas`

- actix-web/postgres/Cargo.toml
- axum/htmx-crud/Cargo.toml
- axum/oauth2/Cargo.toml
- axum/postgres/Cargo.toml
- fullstack-templates/saas/backend/Cargo.toml
- rocket/postgres/Cargo.toml
- rocket/url-shortener/Cargo.toml
- serenity/postgres/Cargo.toml
- shuttle-cron/Cargo.toml
- this is a matching PR to #1838 submitted for the main Shuttle repo
- bumps sqlx to 0.8 in all database examples
- have not done any testing
- I believe that the PR for #1838 in the main repo must be accepted first
> improvement: bump sqlx to 0.8 in database examples

- axum/turso/Cargo.toml
Bumped libsql to 0.6.0 in the Axum Turso example, to coincide with the associated PR in the main Shuttle repo.
I didn't run any tests.
> improvement: update libsql to 0.6.0  in Axum Turso example

- rocket/dyn-templates/Shuttle.toml
This PR includes a fix.
Rocket.toml is added in assets list of Shuttle.toml.
`shuttle deploy` fails, if templates/ folder is renamed, as Rocket.toml is never read (by default rocket will look in folder named templates/, that's why rename is needed for this test).
With this change, Rocket.toml is read and project is deployed correctly.
> rocket: Include Rocket.toml in build assets
